### ISSUE TITLE
Problem with DeepImageSearch

### ISSUE THREAD

**Issue by Bohdanloz** [TechyNilesh/DeepImageSearch#11]
Hi there I have a database with over 50k photos in it and I try to find similar photos in it but it gives me only some similar one but no the same photo that is present in the database. What is the problem? And maybe here is a way to use Deep Image Search without metadata files cause photos are constantly appending to the bd and everything should be done here quick but to create a metadata of this big amount of photos takes up to 20 hours on my vps.

**Comment by TechyNilesh** [comment]
It's possible that the problem lies in the similarity metric being used to compare the images. Similarity metrics such as cosine similarity or Euclidean distance can be effective in finding similar images, but they may not always be able to identify exact matches. Additionally, depending on the complexity of the images and the amount of variation within the database, it's possible that the images may not have enough distinguishing features to make an exact match
